/** 
 *@file : messageFactory 
 *
 *@messageFactory :Load messages for application
 *
 *@author :(Nagaraju SVP Goli - ngoli@ctepl.com) 
 *
 *@Contact :(Umang - ugupta@ctepl.com)
 * 
 *@Contact : (Chenna - yreddy@ctepl.com)
 *
 *@version     VEM2-1.0
 *@date        17-08-2016
 *
 * MODIFICATION HISTORY
 * ===============================================================
 * SNO      DATE        USER                        COMMENTS
 * ===============================================================
 * 01       17-08-2016  Nagaraju SVP Goli           File Created
 * 02       22-08-2016  Nagaraju SVP Goli           Added messages Object
 *
 */
app.factory('messageFactory', function () {
    return {
        getMessage: function (code) {
            /**
             *Message related code property
             *@param code
             */
            var message = {
                "serverError": "Internal application error, please try again later",
                "ERR_USER_2001": "Error occured while saving user",
                "ERR_REQUEST_PROCESS":"Error occured while processing your request, please try again later",
                "INFO_USER_2002": "User created successfully",
                "INFO_USER_2012": "Error occured while updating user details",
                "ERR_USER_2024": "User id should not be empty",
                "ERR_USER_2025": "Please provide first name",
                "ERR_USER_2026": "First name should not exceed 32 characters",
                "ERR_USER_2027": "Last name should not exceed 32 characters",
                "ERR_USER_2028": "Title should not exceed 20 characters",
                "ERR_USER_2029": "Please select your alert preference type",
                "ERR_USER_2030": "Please provide email id",
                "ERR_USER_2031": "Please provide valid email id",
                "ERR_USER_2032": "Please provide valid phone number",
                "ERR_USER_2033": "Phone number can’t be empty when alert preference type is 'Text'",
                "ERR_USER_2034": "Current password is not a valid password",
                "ERR_USER_2035": "Status should not be empty",
                "INFO_USER_2019": "User deactivated successfully ||User activated successfully",
                "INFO_USER_2015": "User deleted successfully",
                "ERR_USER_2037": "Email address is already in use",
                "INFO_USER_2013": "User updated successfully",
                "INFO_USER_UPLOAD_2000": "Users import completed successfully",
                "ERR_USER_UPLOAD_RECORD_2000": "Users import done with failed records",
                "ERR_USER_UPLOAD_RECORDS_2000": "Users import done with all failed records",
                "ERR_USER_UPLOAD_FORMAT_2000": "Uploaded users sheet is not a valid format",
                "ERR_USER_UPLOAD_2000": "Failed to import users",
                "ERR_ROLE_2001": "Please provide a role name",
                "ERR_ROLE_2002": "Please provide a role type",
                "ERR_ROLE_2003": "Please select the role's permissions",
                "ERR_ROLE_2004": "Please select the role's permissions",
                "ERR_ROLE_2005": "Role object should not be empty",
                "ERR_ROLE_2000": "Role id should not be empty",
                "INFO_ROLE_2002": "Role created successfully",
                "INFO_ROLE_2010": "Get role successful",
                "INFO_ROLE_2005": "Role updated successfully",
                "INFO_ROLE_2008": "Role list successful",
                "INFO_ROLE_20012": "This role cannot be deleted as there are users who are still assigned to this role. Please delete the users first.",
                "ERROR_EMAIL_1007":"Email max length to be allowed only 42 characters",
                "INFO_ROLE_20014": "Role deleted successfully",
                "ERR_USER_2100": "Invalid email address",
                "ERR_ROLE_NAME_2001": "Role name should not contain numbers and special characters",
                "ERR_ROLE_2031": "The super EAI admin value should be valid",
                "ERR_ROLE_2032": "The customer support only value should be valid",
                "ERR_USER_2038": "Please provide last name",
                "ERR_USER_2102": "Current password doesn't match our records",
                "ERR_USER_2104": "Choose password should not be empty",
                "ERR_USER_2105": "Repeated password should not be empty",
                "ERR_USER_2106": "Current password should not be empty",
                "ERR_SESSION_1003": "Your session has expired",
                "ERR_SITE_300": "Name should not be empty",
                "ERR_SITE_301": "name should not exceed 50 characters",
                "ERR_SITE_302": "Type should not be empty",
                "ERR_SITE_304": "Address Line 1 should not be empty",
                "ERR_SITE_305": "State should not be empty",
                "ERR_SITE_306": "City should not be empty",
                "ERR_SITE_307": "Zip Code should not be empty",
                "ERR_SITE_309": "Group should not be empty",
                "ERR_SITE_310": "Degree preferences should not be empty",
                "ERR_SITE_312": "Please provide valid nigthly schedule value",
                "ERR_SITE_313": "Site id should not be empty",
                "ERR_SITE_314": "Customer id should not be empty",
                "ERR_SITE_315": "Address Line 1 should not exceed 50 characters",
                "ERR_SITE_316": "Address Line 2 should not exceed 50 characters",
                "ERR_SITE_317": "Please provide valid status value",
                "FAIL_SITE_400": "Failed to create site",
                "SUCCESS_SITE_200": "Site created successfully",
                "FAIL_SITE_401": "Failed to update site",
                "SUCCESS_SITE_201": "Site updated successfully",
                "FAIL_SITE_402": "Failed to get site list",
                "SUCCESS_SITE_202": "Site List successful",
                "FAIL_SITE_403": "Failed to load add site form",
                "SUCCESS_SITE_203": "New site form loaded successfully",
                "FAIL_SITE_404": "Failed to update site status",
                "SUCCESS_SITE_204": "Site status updation successful",
                "FAIL_L_CITY_400": "Failed to load cities",
                "FAIL_L_STATE_400": "Failed to load states",
                "ERR_SITE_319":"Please enter unique store # value",
                "ERR_SITE_320" : "The Zip Code should not contain more than 10 digits",
                "SUCCESS_SITE_208" : "Site deleted successfully",
                "FAIL_SITE_409"  : "The logged in user does not have any Customers assigned",  
                "ERR_CUSTOMERS_LIST_4404":"No customers data found",
               	"SUCCESS_CUSTOMERS_LIST_4200":"Customers data fetched",
               	"ERR_CUSTOMERS_LIST_4500":"Internal error occured while retriving the customers data",
               	"ERR_CUSTOMERID_EMPTY_4404":"No customer found",
               	//"ERR_CUSTOMERS_LIST_4405":"Unable to update customer's status",
               	"SUCCESS_CUSTOMER_STATUS_UPADTE_4201":"Customer's status updated successfully",
               	"ERR_CUSTOMERS_LIST_4405":"Failed to fetch the customer(s) list",
               	"ERR_CUSTOMER_STATUS_4500":"Failed to update customer's status",
               	"ERR_CUSTOMER_FATAL_4500":"Internal Error",
                "INFO_USER_2005":"Password changed successfully",
                "ERR_USER_2006" :"Error occured while changing password",
                "DEVICE_MODEL_NOT_SUPPORTED_532":"Device model not supported",
                "ERR_USER_2012":"Error occured while updating user details",
                "SUCCESS_REGISTER_DEVICE_200":"Device added successfully",
                "ERR_XCSPEC_UNAUTHORISED_5001":"Unauthorized while registering with XCSPEC",
                "ERROR_SQL_SAVE_DEVICE_5003":"Device already registered with this mac id in VEM2.0",
                "ERROR_XCSPEC_ALREADY_REG_5002":"Device is already registered with this MAC ADDRESS in XCSPEC",
                "INFO_STATE_500":"States loaded successfully",
                "FAIL_STATE_501":" Failed to load States",
                "SUCCESS_DEVICE_SET_TEMP_209":"Temperature has been updated successfully",
                "SUCCESS_DEVICE_SET_TSTAT_DATA_211":"Thermostat data has been updated successfully",
                "SUCCESS_DEVICE_SET_CLOCK_212":"Clock has been set successfully",
                "SUCCESS_ACTIVITY_LOG_201" : "Activity log created successfully",
                "DEVICE_REG_VALIDATE_AWS_IOT_REG_FAILED_5022":"Please register device with AWS IoT before connecting",
                "ERR_DEVICE_MACID_EMPTY_502": "Please enter MAC Id",
                "ERROR_DEVICE_NAME_EMPTY_508": "Please enter Device name",
                "ERROR_DEVICE_MODEL_EMPTY_509": "Please enter Model name",
                "ERROR_DEVICE_SITEID_NULL_510": "Please select State",
                "ERROR_DEVICE_AREA_EMPTY_511": "Please select Area name",
                "ERROR_DEVICE_REGTYPE_NULL_511": "Connect to device should not be empty",
                "ERROR_DEVICE_CUSTID_NULL_512": "Customer Id should not be empty",
                "ERROR_DEVICE_DEVTYPE_NULL_513": "Device type should not be empty",
                "ERROR_DEVICE_WIFIKEY_EMPTY_514": "Please enter wifi key",
                "ERROR_DEVICE_UNIT_EMPTY_515": "Please select unit",
                "ERROR_DEVICE_SET_TSTAT_DATA_EMPTY_524":"Thermostat data should not be empty",

                "ERROR_AWS_IOT_REGISTER_DEVICE_5004": "Device is already registered with this MAC ADDRESS in XCSPEC",
                "ERROR_UPDATING_EAI_DEV_ID_DEVICE_5014": "Error occured while updating device details",
                "SUCCESS_UPDATING_DEVICE_DISCONNECT_203":"Successfully disconnected your device from XCSPEC",
                "SUCCESS_UPDATE_DEVICE_204":"Device details updated successfully",
                "SUCCESS_DELETE_DEVICE_206":"Device Deleted successfully",
                "INFO_DELETE_SITE_UPLOAD_SUCCESS_2001":"Succesfully Deleted",
                "ERR_DELETE_SITE_UPLOAD_2002":"Error occured while deleting the upload",
                
                "INFO_SITE_UPLOAD_2000": "Sites import done successfully",
                "ERR_SITE_UPLOAD_RECORD_2000": "Sites import done with some records failing",
                "ERR_SITE_UPLOAD_RECORDS_2000": "Sites import done with all records failing",
                "ERR_SITE_UPLOAD_FORMAT_2000": "Incorrect site bulk import template, please check the format and try again",
                "ERR_SITE_UPLOAD_2000": "Failed to import sites",
                
                
                "ERR_COMPANY_NAME_300":"Company Name should not be empty",
                "ERR_COMPANY_SIZE_301":"Company name should not exceed 50 characters",
                "ERR_CUSTOMER_302":"Customer ID should not be empty",
                "ERR_CUSTOMER_303":"Customer ID should not exceed 10 characters",
                "ERR_CUSTOMER_304":"Address Line 1 should not be empty",
                "ERR_CUSTOMER_305":"State should not be empty",
                "ERR_CUSTOMER_306":"City should not be empty",
                "ERR_CUSTOMER_307":"Zip Code should not be empty",
                "ERR_CUSTOMER_308":"Zip code should not exceed 10 characters",
                "ERR_CUSTOMER_312":"Please provide valid Nigthly Schedule value",
                "ERR_CUSTOMER_313":"Customer ID should not be empty",
                "ERR_CUSTOMER_315":"Address Line 1 should not exceed 50 characters",
                "ERR_CUSTOMER_316":"Address Line 2 should not exceed 50 characters",
                "ERR_CUSTOMER_317":"Please select dropdown status value",
                "ERR_CUSTOMER_2001":"Failed to create customer",
                "INFO_CUSTOMER_2000":"Customer created successfully",
                "INFO_FILE_PNG":"Permitted image types are png or jpeg/jpg",
                "ERR_USER_2110":"User id should not be empty",
                "ERR_CUSTOMER_CODE_2016":"Customer ID is not generated for selected company",
                "ERR_CUSTOMER_CODE_2017":"Customer ID is generated for selected company",
                "ERR_CUSTOMER_CODE_EXISTS_2017":"This Customer ID is already taken, please choose a different Customer ID",
                "INFO_CUSTOMER_201":"Customer updated successfully",
                "ERR_CUSTOMER_2012":"Failed to update Customer",
                "INFO_CUSTOMER_2016":"Customer deleted successfully",	
                "ERR_CUSTOMER_2014":"Failed to delete customer",
                "ERR_CUSTOMER_2015":"Failed to insert the record",
                "ERR_CUSTOMER_20150":"created site details for customer",
                "ERR_FILE_UPLOAD_200":"Failed to upload the file",
                "ERR_USER_2045":"Failed to update the profile details",
                "INFO_USER_2046":"Successfully updated the profile details",
                "INFO_STATUS_APPLY_SCHEDULE_7502":"Schedule download process starting. Please check schedule profile or device profile to see download progress.",
                "INFO_SAVE_GROUP_SUCCESS_6201":"Group created successfully",
                "ERR_SAVEGROUP_6405":"Failed to create group",
                "INFO_SAVE_GROUP_SUCCESS_6203":"Group updated successfully",
                "ERR_SAVEGROUP_6407":"Failed to update group",
            	"INFO_DELETE_GROUP_SUCCESS_6204":"Group deleted successfully",
                "ERR_DELETEGROUP_6408":"Failed to delete group" ,   
                "ERR_DUP_SCHEDULE_8000":"Schedule name already exists. Please choose a different name.",
                "SUCCESS_SCHEDULE_200": "Schedule created successfully",
                "SUCCESS_CUSTOM_SCHEDULE_200": "Custom schedule created and download process started.",
                "ERROR_SCHEDULE_NO_DATA_8002":"Please enter data for atleast one day",
                "ERROR_SCHEDULE_NO_ALL_DATA_8002":"Please fill all days",
                "FAIL_SCHEDULE_400": "Failed to create schedule",
                "SUCCESS_UPDATE_SCHEDULE_200": "Schedule updated successfully",
                "FAIL_UPDATE_SCHEDULE_400": "Failed to update schedule",
                "SUCCESS_DELETE_SCHEDULE_200": "Schedule deleted successfully",
                "FAIL_DELETE_SCHEDULE_400": "Failed to delete schedule",
                "ERROR_COMMON_ZIPCODE_NOTVALIDATE_501":"Please provide valid zip code",
                "ERROR_COMMON_CITY_NOTVALIDATE_501":"Please provide valid city name",
                "ERR_FILE_EMPTY_2047": "Please select image",
                "INFO_USER_2501":"Successfully uploaded the application image",
                "INFO_APP_FILE_PNG":"Please use PNG file with maximum size of 500KB",
                "SUCCESS_SAVECONFIG_7203":"Alert configuration updated successfully",
                "ERROR_ALERT_CUSTOMER_CONFIG_DELETE_7501":"Unable to reset alerts to default configurations",
                "SUCCESS_ALERT_CUSTOMER_CONFIG_DELETE_7208":"Alerts reset to default configurations successfully",
                "ALREADY_ALERT_CUSTOMER_CONFIG_7208":"This is already a default configuration",
                "ERROR_ALERT_ACTIONLIST_7407":"Unable to update action list status",
                "SUCCESS_ALERT_ACTIONLIST_7207":"Action list updated successfully",
                "ERROR_COMMON_STORE_TIMEZONE_502":"The Timezone should not be empty",
                 "CLIENT_SIDE_DEVICE_FORECAST_ERROR_SAME_DATE": "The dates that you have selected is already defined by another forecast. Please select different dates.",
                "CLIENT_SIDE_DEVICE_FORECAST_ERROR_SAME_NAME": "Forecast name is already in use. Please enter other forecast name.",
                "CLIENT_SIDE_DEVICE_FORECAST_ERROR_INVALID_DATES": "To Date should be grater than the from date",
                "CLIENT_SIDE_DEVICE_FORECAST_ERROR_NO_FORECAST": "Please add at least one forecast",
                "SUCCESS_ADD_FORECAST_CONFIG_201": "Forecast has been added successfully",
                "SUCCESS_UPDATE_FORECAST_CONFIG_203": "Forecast has been updated successfully",
                "SUCCESS_DELETE_FORECAST_204": "Forecast is deleted successfully",
                "ERROR_FORECAST_MODE_NULL_500": "Please select forecast Mode",
                "ERROR_FORECAST_TYPE_NULL_501": "Forecast module id is required",
                "ERROR_FORECAST_TYPE_ID_NULL_502": "Module specific id required",
                "ERROR_FORECAST_FORECASTNAME_EMPTY_503": "Please enter forecast name",
                "ERROR_FORECAST_FROMDATE_EMPTY_504": "From date required",
                "ERROR_FORECAST_TODATE_EMPTY_505": "To date required",
                "ERROR_FORECAST_MINTEMP_NULL_507": "Please enter min temparature",
                "ERROR_FORECAST_MAXTEMP_NULL_508": "please enter max temparature",
                "ERROR_ADD_FORECAST_CONFIG_510": "Add forecast failed",
                "ERROR_REPORT_1017": "No devices for current selection",
                "ERROR_ANALYTICS_1005":"A maximum of 8 parameters can be selected at a time",
                "ERR_GROUPCHECK_6406": "Unable to group sites belonging to different customers",
                "ERROR_COMMON_VALIDATE_ZIPCODE_EMPTY_500": "Zip code should not be zero",
                "EMPTY_FILE":"Please upload file",
                "APPLY_TO_ALREADY_EXIST": "Are you sure you want to overwrite the device's current forecast schedule?",
                "SUCCESS_APPLY_FORECAST_CONFIG_201": "Forecast applied successfully",
                "ERR_TIMEZONE_300":"Please provide valid zip code",
                "SUCCESS_RUN_SCHEDULE_203": "Schedule download process started",
                	
            	"ERROR_PDF_REPORT_500": "PDF Report  failed",
                "SUCCESS_PDF_REPORT_200": "PDF Report successfully",
                "ERROR_PDF_REPORT_GET_LIST_500": "PDF Report List failed",
                "SUCCESS_PDF_REPORT_GET_LIST_200": "PDF Report List successfully",
                "ERROR_PDF_REPORT_INSERT_500": "PDF Report created successfully",
                "SUCCESS_PDF_REPORT_INSERT_200": "PDF Report created Failed",
                "ERROR_PDF_REPORT_DELETE_500": "PDF Report deletion Failed",
                "SUCCESS_PDF_REPORT_DELETE_200": "PDF Report deleted successfully",
                "ERROR_PDF_REPORT_RESEND_500": "PDF Report creation Failed",
                "SUCCESS_PDF_REPORT_RESEND_200": "PDF Report resent successfully",
                "FAIL_DELETE_SCHEDULE_401":"Unable to delete, schedule is still mapped to one or more forecast schedules.",
                "FAIL_DELETE_SCHEDULE_402":"Unable to delete, schedule is still mapped to one or more devices.",
                "FAIL_SITE_411":"Site Name is already Exists",
                "FAIL_GEOCODEDATA_DETAILS_400":"Please enter valid zip code",
                "FAIL_GEOCODEDATA_DETAILS_CITY_400":"Please enter valid city name",
                "FAIL_GEOCODEDATA_DETAILS_STATE_400":"Please enter valid state name",
                "FAIL_GEOCODEDATA_DETAILS_STATE_CITY_400":"Please enter valid state and city names",
                "ERROR_ANALYTICS_1009":"Analytics cannot be compared for devices belonging to different time zones",
                "FAIL_GEOCODEDATA_DETAILS_ANY_400":"Invalid address. Please verify your city, state and zip code.",
                "SUCCESS_UPDATING_DEVICE_STATUS_202":"Successfully updated the device status",
                "ERROR_UPDATE_DEVICE_STATUS_5006":"Error occured while updating the device status",
                "ERROR_SQL_UPDATE_DEVICE_ALREADY_INVEM_5019":"Device already registered with this mac id in VEM2.0",
                "FAIL_SITE_LAT_LON_400":"Address is invalid.",
                "ERR_USER_2502":"Error occured while updating user Email ID.",
                "ERROR_USER_EMAIL_UPDATE": "Incorrect password details.",
                "INFO_USER_2503":"Successfully updated the user Email ID."
                
            }
            return (message[code]) ? message[code] : message.ERR_REQUEST_PROCESS;
        }
    }
})
